Solution for Task_5_2
debrikosar/prices_task pull request #1
Opened 2020-02-10 10:29 UTC by debrikosar

2020-02-19 08:34 UTC, esmoke requested changes
In general code is readable and looks quite accurate but we need to refactor some moments:
1. Separate functions which do business logic(calculations in our case) from logic which works with files - this allows to write unit tests.
2. Change signatures of methods to accept data collection instead of iterators.
3. Extract business logic functions into separate file.
4. Don't do seek(0) - just read data from the input file and put it into collection.
5. You can check DictReader instead of StreamReader but this up to you to decide.

2020-02-25 14:10 UTC, alex-tsukanov commented on calculations.py
> +            user_statistic[line[user_column_index]] += 1
`defaultdict` or `Counter` would be much easier to use https://docs.python.org/3.8/library/collections.html

2020-02-25 14:10 UTC, alex-tsukanov commented on calculations.py
> +        average_prices_list[item[item_id_index]] = sum([float(price) for price in average_prices_list[item[item_id_index]]]) \
please use generator expression inside `sum`

2020-02-26 08:22 UTC, alex-tsukanov commented
File naming is inconsistent: `calculations.py` but `Prices.py`. You should follow [PEP8](https://www.python.org/dev/peps/pep-0008/#package-and-module-names) unless there's a specific reason not to do this.

2020-02-26 08:33 UTC, alex-tsukanov commented on Prices.py
> +        input_file_processing(result.data_address)
I recommend to safely open the file [this way](https://docs.quantifiedcode.com/python-anti-patterns/readability/asking_for_permission_instead_of_forgiveness_when_working_with_files.html). Explaination: https://stackoverflow.com/a/12270384/7541374

2020-02-26 08:35 UTC, alex-tsukanov commented on calculations.py
> +    average_prices_list = generate_empty_average_prices_list(data)
maybe use `defaultdict(list)` here?

2020-02-26 08:36 UTC, alex-tsukanov commented on calculations.py
> +        else:
use `elif`, no need for extra level of nesting

2020-02-26 08:43 UTC, alex-tsukanov commented on calculations.py
> +    return items_id_list
It's better to use set, not list, so that you don't need to check if value was already added. You can also use a comprehension instead of the loop

2020-02-26 08:43 UTC, alex-tsukanov commented on calculations.py
> +    return shop_id_list
same as for `generate_unique_items_list`

2020-02-27 11:15 UTC, alex-tsukanov commented on calculations.py
> +        average_prices_list[item[item_id_index]] = sum((float(price) for price in average_prices_list[item[item_id_index]])) \
and you can also omit extra parentheses

2020-02-27 13:04 UTC, aliaksandr-tsukanau requested changes

2020-02-27 13:04 UTC, aliaksandr-tsukanau commented on calculations.py
> +    return highest_activity_user[username_index]
FYI it's more convenient to iterate over dictionary like this:
```python
for user, reviews in user_statistic.items():
```
But all you need here is to find user with highest number of reviews. You can do it this way:
```python
user_statistic = generate_user_statistic(data)
return max(user_statistic, key=lambda user: user_statistic[user])
```

2020-02-27 13:04 UTC, aliaksandr-tsukanau commented on calculations.py
> +                min_price_item = line
wrong indentation

2020-02-27 13:04 UTC, aliaksandr-tsukanau commented on calculations.py
> +            unique_shop_items[line[store_id_column_index]].append(line[item_id_column_index])
I can suggest this:
```python
unique_shop_items = defaultdict(list)
for line in data:
    item_id, store_id, _ = line
    unique_shop_items[store_id].append(item_id)
```

2020-02-27 13:04 UTC, alex-tsukanov commented on prices.py
> +    price_index = 2
this indices are constants for the project. Maybe let's move them into global scope not to define each time?
```python
ITEM_ID_INDEX = 0
STORE_ID_INDEX = 1
PRICE_INDEX = 2
```
It's fine to have globals as long as they are constant

2020-02-27 13:04 UTC, alex-tsukanov commented on prices.py
> +    with open('Data_Output/' + filename + '_general_statistic.csv', 'w', newline='') as file:
Use `os.path.join` or `pathlib` to concatenate paths. Current code will fail on some OSes

2020-03-02 09:06 UTC, aliaksandr-tsukanau approved these changes

2020-03-02 17:20 UTC, esmoke approved these changes

2020-03-02 17:20 UTC, esmoke commented
LGTM

2020-03-04 06:41 UTC, merged